apiVersion: v1
kind: Namespace
metadata:
  name: echo-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-env-deploy
  namespace: echo-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-env
  template:
    metadata:
      labels:
        app: echo-env
    spec:
      containers:
      - name: echo-env
        image: prefix/echo-env:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-env-service
  namespace: echo-env
spec:
  selector:
    app: echo-env
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP